# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, time, urllib.request, json, time, simplekml, math
from time import sleep
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, QThread, pyqtSignal, Qt
from PyQt5.QtWidgets import (
    QApplication,
    QLabel,
    QMainWindow,
    QPushButton,
    QVBoxLayout,
    QWidget,
    QLineEdit,

)

roll = 0
pitch = 0
yaw = 0
heading = 0

time = 0
lon = 0
lat = 0
alt = 0
vel = 0
fix = 0
sats = 0

started = False
x= 0


kml = simplekml.Kml()
print('start')

pnt = kml.newpoint(name="Aircraft", description="Generic aircraft",
                coords=[(18.432314,-33.988862)])  # lon, lat, alt
pnt.style.iconstyle.icon.href = 'airports.png'
pnt.altitudemode = simplekml.AltitudeMode.relativetoground #altitude

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'

print(bcolors.OKCYAN + "Mavlink to KML pipe by mnux" + bcolors.ENDC)



class Worker(QObject):
    finished = pyqtSignal()
    progress = pyqtSignal(int)

    def run(self):
        global started

        global roll
        global pitch
        global yaw
        global heading

        global time
        global lon
        global lat
        global alt
        global vel
        global fix
        global sats

        while True: #main loop
                with urllib.request.urlopen("http://127.0.0.1:56781/mavlink/") as url:
                    mav = json.load(url)

                roll = math.degrees(mav["ATTITUDE"]["msg"]["roll"])
                pitch = math.degrees(mav["ATTITUDE"]["msg"]["pitch"])
                yaw = math.degrees(mav["ATTITUDE"]["msg"]["yaw"])
                heading =  mav["VFR_HUD"]["msg"]["heading"]

                time = mav["GPS_RAW_INT"]["msg"]["time_usec"]
                lon = mav["GPS_RAW_INT"]["msg"]["lon"] * 0.0000001
                lat = mav["GPS_RAW_INT"]["msg"]["lat"] * 0.0000001
                alt = 10 #mav["GPS_RAW_INT"]["msg"]["alt"] * 0.001
                vel = mav["GPS_RAW_INT"]["msg"]["vel"] * 0.001
                fix = mav["GPS_RAW_INT"]["msg"]["fix_type"]
                if fix == 3:
                    fix = "3D FIX"
                elif fix == 2:
                    fix = "2D FIX"
                elif fix == 1:
                    fix = "NO FIX"

                pnt.style.iconstyle.heading = heading
                pnt.style.iconstyle.size = 3
                sats = mav["GPS_RAW_INT"]["msg"]["satellites_visible"]
                pnt.lookat.gxaltitudemode = simplekml.GxAltitudeMode.relativetoseafloor
                pnt.coords=[(lon, lat, alt) ]  # lon, lat optional height
                pnt.camera.heading = heading
                pnt.camera.roll = roll
                pnt.camera.latitude = lat
                pnt.camera.longitude = lon
                pnt.camera.altitude = alt
                pnt.camera.tilt = 90
                kml.save("out.kml")#update kml
                print(lon, lat, alt, vel, fix, sats) #serial print
                sleep(0.1)
                self.progress.emit(lon) #no idea why this is here
        self.finished.emit()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(654, 376)
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        MainWindow.setFont(font)
        icon = QtGui.QIcon.fromTheme("preferences-system-network")
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(510, 270, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setChecked(False)
        self.pushButton_2.clicked.connect(self.run)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(440, 60, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(440, 20, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(370, 60, 51, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(370, 20, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(370, 200, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(470, 200, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(540, 200, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(370, 100, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(440, 100, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(370, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(510, 0, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(370, 140, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(440, 140, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 0, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(10, 60, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(10, 100, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(10, 140, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(130, 290, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.stateChanged.connect(self.waypoint)
        self.checkBox.setGeometry(QtCore.QRect(10, 290, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(260, 290, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(440, 290, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(390, 290, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(100, 20, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(100, 60, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(100, 100, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, -10, 20, 291))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(160, 140, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(10, 180, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_34.setFont(font)
        self.label_34.setText("")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(160, 180, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_35.setFont(font)
        self.label_35.setText("")
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(10, 220, 141, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(26)
        font.setBold(False)
        font.setItalic(False)
        self.label_36.setFont(font)
        self.label_36.setText("")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(160, 220, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Open Sans")
        font.setPointSize(31)
        font.setBold(True)
        font.setItalic(False)
        self.label_37.setFont(font)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 654, 22))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionsecret_3 = QtWidgets.QAction(MainWindow)
        self.actionsecret_3.setObjectName("actionsecret_3")
        self.menuEdit.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def waypoint(self):
        # printing the checked status
        if self.checkBox.isChecked():
            waypointcoord = self.lineEdit.text()
            pnt = kml.newpoint(name="Waypoint", description="A waypoint set from the Mavlink to KML pipe", coords=[(waypointcoord)])  # lon, lat, alt
            pnt.altitudemode = simplekml.AltitudeMode.relativetoground #altitude
            print("Setting waypoint to:", self.lineEdit.text())
            kml.save("out.kml")#update kml
        else:
            print("Removing waypoint.")


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mavlink to KML pipe"))
        self.pushButton_2.setText(_translate("MainWindow", "START"))
        self.label_10.setText(_translate("MainWindow", "N/A"))
        self.label_11.setText(_translate("MainWindow", "N/A"))
        self.label_12.setText(_translate("MainWindow", "lat:"))
        self.label_13.setText(_translate("MainWindow", "lon:"))
        self.label_15.setText(_translate("MainWindow", "N/A"))
        self.label_16.setText(_translate("MainWindow", "sats:"))
        self.label_17.setText(_translate("MainWindow", "N/A"))
        self.label_14.setText(_translate("MainWindow", "alt:"))
        self.label_18.setText(_translate("MainWindow", "N/A"))
        self.label_19.setText(_translate("MainWindow", "GPS info:"))
        self.label_20.setText(_translate("MainWindow", "N/A"))
        self.label_21.setText(_translate("MainWindow", "vel:"))
        self.label_22.setText(_translate("MainWindow", "N/A"))
        self.label_23.setText(_translate("MainWindow", "Attitude:"))
        self.label_24.setText(_translate("MainWindow", "roll:"))
        self.label_25.setText(_translate("MainWindow", "ptch:"))
        self.label_26.setText(_translate("MainWindow", "yaw:"))
        self.label_27.setText(_translate("MainWindow", "heading:"))
        self.checkBox.setText(_translate("MainWindow", "Waypoint"))
        self.label_28.setText(_translate("MainWindow", "(lon, lat, alt)"))
        self.label_29.setText(_translate("MainWindow", "rate:"))
        self.label_30.setText(_translate("MainWindow", "N/A"))
        self.label_31.setText(_translate("MainWindow", "N/A"))
        self.label_32.setText(_translate("MainWindow", "N/A"))
        self.label_33.setText(_translate("MainWindow", "N/A"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuFile.setTitle(_translate("MainWindow", "Settings"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionsecret_3.setText(_translate("MainWindow", "secret :3"))


    def reportProgress(self, n):
        self.label_30.setText(format(roll))
        self.label_31.setText(format(pitch))
        self.label_32.setText(format(yaw))
        self.label_33.setText(format(heading))

        self.label_20.setText(format(time))
        self.label_11.setText(format(lon))
        self.label_10.setText(format(lat))
        self.label_18.setText(format(alt))
        self.label_22.setText(format(vel))
        self.label_15.setText(format(fix))
        self.label_17.setText(format(sats))


    def run(self):
         # Step 2: Create a QThread object
        started = True
        self.thread = QThread()
        # Step 3: Create a worker object
        self.worker = Worker()
        # Step 4: Move worker to the thread
        self.worker.moveToThread(self.thread)
        # Step 5: Connect signals and slots
        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)
        self.worker.progress.connect(self.reportProgress)
        # Step 6: Start the thread
        self.thread.start()

        # Final resets
        self.pushButton_2.setText("STOP")
        self.thread.finished.connect(
            lambda: self.pushButton_2.setEnabled(True)
        )
        self.thread.finished.connect(
            lambda: self.pushButton_2.setText("START")
        )




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
